# Generated by Django 2.2.2 on 2019-07-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_productincart'),
    ]

    operations = [
        migrations.AddField(
            model_name='productincart',
            name='session_key',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
